name: grossnax
recipe: drupal8
config:
  framework: drupal8
  webroot: ./web/
  index: false
  edge: false
  cache: false
  xdebug: true
services:
  node:
    type: node
    build:
      - cd $LANDO_MOUNT && npm it
  pma:
    type: phpmyadmin
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
